# Generated by Django 3.1.12 on 2021-06-26 06:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, height_field='height', upload_to='covers/', verbose_name='cover', width_field='width'),
        ),
    ]
