# Generated by Django 3.1.12 on 2021-06-26 06:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210626_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='covers/', verbose_name='cover'),
        ),
    ]
